"""add address columns to routes

Revision ID: 304857bc1f56
Revises: d30271ffec11
Create Date: 2026-05-14 21:32:46.561325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304857bc1f56'
down_revision: Union[str, Sequence[str], None] = 'd30271ffec11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('start_address', sa.String(length=512), nullable=True))
    op.add_column('routes', sa.Column('end_address', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'end_address')
    op.drop_column('routes', 'start_address')
    # ### end Alembic commands ###
